import { ReactFlowNodeId } from "@/shared/react-flow/nodes";

import {
  AMMETER_CELL_04KV_INPUT_RENDER_DATA,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_INPUT_RENDER_DATA,
  SWITCH_CELL_04KV_INPUT_RENDER_DATA,
  VOLTMETER_CELL_04KV_INPUT_RENDER_DATA,
  FUSE_CELL_04KV_INPUT_RENDER_DATA,
  AMMETER_CELL_04KV_LABEL,
  FUSE_CELL_04KV_LABEL,
  SWITCH_CELL_04KV_LABEL,
  VOLTMETER_CELL_04KV_LABEL,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL,
  AMMETER_CELL_04KV_KEY_1,
  FUSE_CELL_04KV_KEY_1,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_KEY_1,
  SWITCH_CELL_04KV_KEY_1,
  VOLTMETR_CELL_04KV_KEY_1,
} from "@/shared/react-flow/nodes/cell-04kv/options";
import { TNonPrimitiveKeysTCell04KvDataKeys } from "@/shared/react-flow/nodes/cell-04kv/types";

import {
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_KEY_1,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL,
  MICROPROCESSOR_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  MICROPROCESSOR_DEVICE_CELL_10KV_KEY_1,
  MICROPROCESSOR_DEVICE_CELL_10KV_LABEL,
  OPN_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  OPN_DEVICE_CELL_10KV_KEY_1,
  OPN_DEVICE_CELL_10KV_LABEL,
  SWITCHING_DEVICE_R_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_R_CELL_10KV_KEY_1,
  SWITCHING_DEVICE_R_CELL_10KV_LABEL,
  SWITCHING_DEVICE_R_CELL_10KV_PARAM,
  SWITCHING_DEVICE_VN_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VN_CELL_10KV_KEY_1,
  SWITCHING_DEVICE_VN_CELL_10KV_LABEL,
  SWITCHING_DEVICE_VN_CELL_10KV_PARAM,
  SWITCHING_DEVICE_VV_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VV_CELL_10KV_KEY_1,
  SWITCHING_DEVICE_VV_CELL_10KV_LABEL,
  SWITCHING_DEVICE_VV_CELL_10KV_PARAM,
  TSN_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  TSN_DEVICE_CELL_10KV_KEY_1,
  TSN_DEVICE_CELL_10KV_LABEL,
  UKRM_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  UKRM_DEVICE_CELL_10KV_KEY_1,
  UKRM_DEVICE_CELL_10KV_LABEL,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_KEY_1,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_LABEL,
} from "@/shared/react-flow/nodes/cell-10kv/options";
import { TNonPrimitiveKeysTCell10KvDataKeys } from "@/shared/react-flow/nodes/cell-10kv/types";
import {
  MODEL_SECTION_10KV_INPUT_RENDER_DATA,
  MODEL_SECTION_10KV_LABEL,
} from "@/shared/react-flow/nodes/section-10kv/options";
import { TNonPrimitiveKeysTSection10KvDataKeys } from "@/shared/react-flow/nodes/section-10kv/types";

type InputRenderDataCell10Kv =
  | typeof TSN_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof UKRM_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_R_CELL_10KV_INPUT_RENDER_DATA
  | typeof OPN_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof MICROPROCESSOR_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_INPUT_RENDER_DATA;

type InputRenderDataSection10Kv = typeof MODEL_SECTION_10KV_INPUT_RENDER_DATA;
type InputRenderDataCell04Kv =
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_INPUT_RENDER_DATA
  | typeof AMMETER_CELL_04KV_INPUT_RENDER_DATA
  | typeof SWITCH_CELL_04KV_INPUT_RENDER_DATA
  | typeof VOLTMETER_CELL_04KV_INPUT_RENDER_DATA
  | typeof FUSE_CELL_04KV_INPUT_RENDER_DATA;

type InputsCell04KvLabel =
  | typeof AMMETER_CELL_04KV_LABEL
  | typeof FUSE_CELL_04KV_LABEL
  | typeof SWITCH_CELL_04KV_LABEL
  | typeof VOLTMETER_CELL_04KV_LABEL
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL;

type InputsCell10KvLabel =
  | typeof TSN_DEVICE_CELL_10KV_LABEL
  | typeof UKRM_DEVICE_CELL_10KV_LABEL
  | typeof VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_R_CELL_10KV_LABEL
  | typeof OPN_DEVICE_CELL_10KV_LABEL
  | typeof MICROPROCESSOR_DEVICE_CELL_10KV_LABEL
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL;
type InputsSection10KvLabel = typeof MODEL_SECTION_10KV_LABEL;
type InputPropertiesKey1_CELL_10KV =
  // | typeof TSN_DEVICE_CELL_10KV_KEY_1
  // | typeof VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_KEY_1
  // | typeof SWITCHING_DEVICE_VV_CELL_10KV_KEY_1
  // | typeof SWITCHING_DEVICE_VN_CELL_10KV_KEY_1
  // | typeof SWITCHING_DEVICE_R_CELL_10KV_KEY_1
  // | typeof OPN_DEVICE_CELL_10KV_KEY_1
  // | typeof MICROPROCESSOR_DEVICE_CELL_10KV_KEY_1
  // | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_KEY_1
  // | typeof UKRM_DEVICE_CELL_10KV_KEY_1;
  TNonPrimitiveKeysTCell10KvDataKeys;
type InputPropertiesKey1_CELL_04KV =
  // | typeof AMMETER_CELL_04KV_KEY_1
  // | typeof FUSE_CELL_04KV_KEY_1
  // | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_KEY_1
  // | typeof SWITCH_CELL_04KV_KEY_1
  // | typeof VOLTMETR_CELL_04KV_KEY_1;
  TNonPrimitiveKeysTCell04KvDataKeys;

type Param10Kv =
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_PARAM
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_PARAM
  | typeof SWITCHING_DEVICE_R_CELL_10KV_PARAM;
export type GenericInputsProps = {
  className?: string;
  selectedNodeId: ReactFlowNodeId;
  // inputProperties?: TNonPrimitiveKeysCell04KvData | TNonPrimitiveKeysCell10KvData;
  inputProperties?: Record<string, string | number>;
  inputRenderData: InputRenderDataCell04Kv | InputRenderDataCell10Kv | InputRenderDataSection10Kv;

  inputsLabel: InputsCell10KvLabel | InputsCell04KvLabel | InputsSection10KvLabel;

  inputPropertiesKey1:
    | InputPropertiesKey1_CELL_10KV
    | InputPropertiesKey1_CELL_04KV
    | TNonPrimitiveKeysTSection10KvDataKeys;

  param?: Param10Kv | string;
};
