import SHINA_BOTTOM_LEFT from "./SHINA_BOTTOM_LEFT.svg"
import SHINA_BOTTOM_RIGHT from "./SHINA_BOTTOM_RIGHT.svg"
import SHINA_HEADER from "./SHINA_HEADER.svg"
import SHINA_HEADER_EMPTY from "./SHINA_HEADER_EMPTY.svg"
import TAIL from "./TAIL.svg"

export { SHINA_BOTTOM_LEFT, SHINA_BOTTOM_RIGHT, SHINA_HEADER, SHINA_HEADER_EMPTY, TAIL }