import { ReactFlowNodeId } from "@/shared/react-flow/nodes/shared";

import {
  AMMETER_CELL_04KV_INPUT_RENDER_DATA,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_INPUT_RENDER_DATA,
  SWITCH_CELL_04KV_INPUT_RENDER_DATA,
  VOLTMETER_CELL_04KV_INPUT_RENDER_DATA,
  FUSE_CELL_04KV_INPUT_RENDER_DATA,
  AMMETER_CELL_04KV_LABEL,
  FUSE_CELL_04KV_LABEL,
  SWITCH_CELL_04KV_LABEL,
  VOLTMETER_CELL_04KV_LABEL,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL,
} from "@/shared/react-flow/nodes/cells/cell-04kv/options";
import { TNonPrimitiveDataKeysTCell04Kv } from "@/shared/react-flow/nodes/cells/cell-04kv/types";

import {
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL,
  MICROPROCESSOR_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  MICROPROCESSOR_DEVICE_CELL_10KV_LABEL,
  OPN_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  OPN_DEVICE_CELL_10KV_LABEL,
  SWITCHING_DEVICE_R_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_R_CELL_10KV_LABEL,
  SWITCHING_DEVICE_R_CELL_10KV_PARAM,
  SWITCHING_DEVICE_VN_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VN_CELL_10KV_LABEL,
  SWITCHING_DEVICE_VN_CELL_10KV_PARAM,
  SWITCHING_DEVICE_VV_CELL_10KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VV_CELL_10KV_LABEL,
  SWITCHING_DEVICE_VV_CELL_10KV_PARAM,
  TSN_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  TSN_DEVICE_CELL_10KV_LABEL,
  UKRM_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  UKRM_DEVICE_CELL_10KV_LABEL,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_INPUT_RENDER_DATA,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_LABEL,
} from "@/shared/react-flow/nodes/cells/cell-10kv/options";
import { TNonPrimitiveDataKeysTCell10Kv } from "@/shared/react-flow/nodes/cells/cell-10kv/types";
import {
  POWER_TRANSFORMER_1004KV_INPUT_RENDER_DATA,
  POWER_TRANSFORMER_1004KV_KEY_1,
  POWER_TRANSFORMER_1004KV_LABEL,
} from "@/shared/react-flow/nodes/power-transformer-10-04kv/options";
import {
  MODEL_SECTION_10KV_INPUT_RENDER_DATA,
  MODEL_SECTION_10KV_LABEL,
} from "@/shared/react-flow/nodes/sections/section-10kv/options";
import {
  MODEL_SECTION_35KV_INPUT_RENDER_DATA,
  MODEL_SECTION_35KV_KEY_1,
  MODEL_SECTION_35KV_LABEL,
} from "@/shared/react-flow/nodes/sections/section-35kv/options";
import {
  POWER_TRANSFORMER_3510KV_INPUT_RENDER_DATA,
  POWER_TRANSFORMER_3510KV_LABEL,
} from "@/shared/react-flow/nodes/power-transformer-35-10kv";
import {
  MODEL_SECTION_04KV_INPUT_RENDER_DATA,
  MODEL_SECTION_04KV_LABEL,
} from "@/shared/react-flow/nodes/sections/section-04kv/options";

type InputRenderDataCell10Kv =
  | typeof TSN_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof UKRM_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_INPUT_RENDER_DATA
  | typeof SWITCHING_DEVICE_R_CELL_10KV_INPUT_RENDER_DATA
  | typeof OPN_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof MICROPROCESSOR_DEVICE_CELL_10KV_INPUT_RENDER_DATA
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_INPUT_RENDER_DATA;

type InputRenderDataSection10Kv = typeof MODEL_SECTION_10KV_INPUT_RENDER_DATA;
type InputRenderDataCell04Kv =
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_INPUT_RENDER_DATA
  | typeof AMMETER_CELL_04KV_INPUT_RENDER_DATA
  | typeof SWITCH_CELL_04KV_INPUT_RENDER_DATA
  | typeof VOLTMETER_CELL_04KV_INPUT_RENDER_DATA
  | typeof FUSE_CELL_04KV_INPUT_RENDER_DATA;

type InputRenderDataPt1004Kv = typeof POWER_TRANSFORMER_1004KV_INPUT_RENDER_DATA;

type InputsCell04KvLabel =
  | typeof AMMETER_CELL_04KV_LABEL
  | typeof FUSE_CELL_04KV_LABEL
  | typeof SWITCH_CELL_04KV_LABEL
  | typeof VOLTMETER_CELL_04KV_LABEL
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL;

type InputsCell10KvLabel =
  | typeof TSN_DEVICE_CELL_10KV_LABEL
  | typeof UKRM_DEVICE_CELL_10KV_LABEL
  | typeof VOLTAGE_TRANSFORMER_DEVICE_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_LABEL
  | typeof SWITCHING_DEVICE_R_CELL_10KV_LABEL
  | typeof OPN_DEVICE_CELL_10KV_LABEL
  | typeof MICROPROCESSOR_DEVICE_CELL_10KV_LABEL
  | typeof MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL;
type InputsSection10KvLabel = typeof MODEL_SECTION_10KV_LABEL;

type InputsPt1004KvLabel = typeof POWER_TRANSFORMER_1004KV_LABEL;
type InputPropertiesKey1_CELL_10KV = TNonPrimitiveDataKeysTCell10Kv;
type InputPropertiesKey1_CELL_04KV = TNonPrimitiveDataKeysTCell04Kv;
type InputPropertiesKey1_POWER_TRANSFORMER_1004Kv = typeof POWER_TRANSFORMER_1004KV_KEY_1;
type Param10Kv =
  | typeof SWITCHING_DEVICE_VV_CELL_10KV_PARAM
  | typeof SWITCHING_DEVICE_VN_CELL_10KV_PARAM
  | typeof SWITCHING_DEVICE_R_CELL_10KV_PARAM;
export type GenericInputsProps = {
  className?: string;
  selectedNodeId: ReactFlowNodeId;
  // inputProperties?: TNonPrimitiveKeysCell04KvData | TNonPrimitiveKeysCell10KvData;
  inputProperties?: Record<string, string | number>;
  inputRenderData:
    | InputRenderDataCell04Kv
    | InputRenderDataCell10Kv
    | InputRenderDataSection10Kv
    | InputRenderDataPt1004Kv
    | typeof MODEL_SECTION_35KV_INPUT_RENDER_DATA
    | typeof POWER_TRANSFORMER_3510KV_INPUT_RENDER_DATA
    | typeof MODEL_SECTION_04KV_INPUT_RENDER_DATA;

  inputsLabel:
    | InputsCell10KvLabel
    | InputsCell04KvLabel
    | InputsSection10KvLabel
    | InputsPt1004KvLabel
    | typeof MODEL_SECTION_35KV_LABEL
    | typeof POWER_TRANSFORMER_3510KV_LABEL
    | typeof MODEL_SECTION_04KV_LABEL;

  inputPropertiesKey1:
    | InputPropertiesKey1_CELL_10KV
    | InputPropertiesKey1_CELL_04KV
    | InputPropertiesKey1_POWER_TRANSFORMER_1004Kv
    | typeof MODEL_SECTION_35KV_KEY_1;

  param?: Param10Kv | string;
};
