import { ReactFlowNodeId } from "@/shared/react-flow/nodes/shared";

import {
  TYPE_OF_FUSE_CELL_04KV_OPTIONS,
  TYPE_OF_FUSE_CELL_04KV_LABEL,
  TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL,
  TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_KEY_1,
  TYPE_OF_FUSE_CELL_04KV_KEY_1,
} from "@/shared/react-flow/nodes/cells/cell-04kv/options";
import {
  TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_KEY_1,
  TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_KEY_1,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_LABEL,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_OPTIONS,
  TYPE_OF_OPN_DEVICE_CELL_10KV_KEY_1,
  TYPE_OF_OPN_DEVICE_CELL_10KV_LABEL,
  TYPE_OF_OPN_DEVICE_CELL_10KV_OPTIONS,
  TYPE_OF_SWITCHING_DEVICE_CELL_10KV_KEY_1,
  TYPE_OF_SWITCHING_DEVICE_CELL_10KV_LABEL,
} from "@/shared/react-flow/nodes/cells/cell-10kv/options";

type SelectOptions10Kv =
  // | typeof TYPE_OF_SWITCHING_DEVICE_CELL_10KV_OPTIONS
  | typeof TYPE_OF_OPN_DEVICE_CELL_10KV_OPTIONS
  | typeof TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_OPTIONS
  | readonly string[];
// | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_OPTIONS;
type SelectOptions04Kv =
  // | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_OPTIONS
  readonly string[] | typeof TYPE_OF_FUSE_CELL_04KV_OPTIONS;
type SelectLabel10Kv =
  | typeof TYPE_OF_SWITCHING_DEVICE_CELL_10KV_LABEL
  | typeof TYPE_OF_OPN_DEVICE_CELL_10KV_LABEL
  | typeof TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_LABEL
  | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_LABEL;
type SelectLabel04Kv =
  | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_LABEL
  | typeof TYPE_OF_FUSE_CELL_04KV_LABEL;

type SelectPropertyKey1_CELL_10KV =
  | typeof TYPE_OF_SWITCHING_DEVICE_CELL_10KV_KEY_1
  | typeof TYPE_OF_OPN_DEVICE_CELL_10KV_KEY_1
  | typeof TYPE_OF_MICROPROCESSOR_DEVICE_CELL_10KV_KEY_1
  | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_10KV_KEY_1;
type SelectPropertyKey1_CELL_04KV =
  | typeof TYPE_OF_MEASURING_CURRENT_TRANSFORMERS_DEVICE_CELL_04KV_KEY_1
  | typeof TYPE_OF_FUSE_CELL_04KV_KEY_1;
export type GenericInputsWithSelectProps = {
  className?: string;
  selectedNodeId: ReactFlowNodeId;
  selectValue?: string;
  selectOptions: SelectOptions10Kv | SelectOptions04Kv;

  selectLabel: SelectLabel10Kv | SelectLabel04Kv | string;

  selectPropertyKey1: SelectPropertyKey1_CELL_10KV | SelectPropertyKey1_CELL_04KV | string;
};
