// тут хранятся непосредственно константы (я уже не знаю как называть эти папочки). Все типы, строго из ../types

export {
  TYPE_OF_CELL_35KV_KEY_1,
  TYPE_OF_CELL_35KV_LABEL,
  TYPE_OF_CELL_CELL_35KV_OPTIONS,
} from "./type-of-cell-consatnts";

export {
  TYPE_OF_SWITCHING_DEVICE_CELL_35KV_OPTIONS,
  TYPE_OF_SWITCHING_DEVICE_CELL_35KV_KEY_1,
  TYPE_OF_SWITCHING_DEVICE_CELL_35KV_LABEL,
} from "./type-of-switching-device-constants";

export {
  TSN_DEVICE_CELL_35KV_INPUT_RENDER_DATA,
  TSN_DEVICE_CELL_35KV_KEY_1,
  TSN_DEVICE_CELL_35KV_LABEL,
} from "./tsn-device-constants";

export {
  VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_INPUT_RENDER_DATA as VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_INPUT_RENDER_DATA,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_KEY_1 as VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_KEY_1,
  VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_LABEL as VOLTAGE_TRANSFORMER_DEVICE_CELL_35KV_LABEL,
} from "./voltage-transformer-device-constants";

export {
  SWITCHING_DEVICE_VV_CELL_35KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VV_CELL_35KV_KEY_1,
  SWITCHING_DEVICE_VV_CELL_35KV_LABEL,
  SWITCHING_DEVICE_VV_CELL_35KV_PARAM,
} from "./switching-device-vv-constants";

export {
  SWITCHING_DEVICE_VN_CELL_35KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_VN_CELL_35KV_KEY_1,
  SWITCHING_DEVICE_VN_CELL_35KV_LABEL,
  SWITCHING_DEVICE_VN_CELL_35KV_PARAM,
} from "./switching-device-vn-constants";

export {
  SWITCHING_DEVICE_R_CELL_35KV_INPUT_RENDER_DATA,
  SWITCHING_DEVICE_R_CELL_35KV_KEY_1,
  SWITCHING_DEVICE_R_CELL_35KV_LABEL,
  SWITCHING_DEVICE_R_CELL_35KV_PARAM,
} from "./switching-device-r-constants";

export {
  OPN_DEVICE_CELL_35KV_INPUT_RENDER_DATA,
  OPN_DEVICE_CELL_35KV_KEY_1,
  OPN_DEVICE_CELL_35KV_LABEL,
  TYPE_OF_OPN_DEVICE_CELL_35KV_KEY_1,
  TYPE_OF_OPN_DEVICE_CELL_35KV_LABEL,
  TYPE_OF_OPN_DEVICE_CELL_35KV_OPTIONS,
} from "./opn-device-constants";

export {
  MICROPROCESSOR_DEVICE_CELL_35KV_INPUT_RENDER_DATA,
  MICROPROCESSOR_DEVICE_CELL_35KV_KEY_1,
  MICROPROCESSOR_DEVICE_CELL_35KV_LABEL,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_35KV_KEY_1,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_35KV_LABEL,
  TYPE_OF_MICROPROCESSOR_DEVICE_CELL_35KV_OPTIONS,
} from "./mircoprocessor-device-constants";

export {
  RATED_CURRENT_OF_THE_MAIN_CIRCUITS_KEY_1,
  RATED_CURRENT_OF_THE_MAIN_CIRCUITS_LABEL,
  RATED_CURRENT_OF_THE_MAIN_CIRCUITS_OPTIONS,
} from "./rated-current-of-the-main-circuits";
